<?php

namespace App\Console\Commands;

use App\Services\ElevenLabsService;
use Illuminate\Console\Command;

class CleanupAudioFiles extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'audio:cleanup {--hours=24 : Number of hours after which files should be deleted}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Clean up old audio files generated by ElevenLabs';

    /**
     * Execute the console command.
     */
    public function handle(ElevenLabsService $elevenLabsService)
    {
        $hours = $this->option('hours');
        
        $this->info("Cleaning up audio files older than {$hours} hours...");
        
        $elevenLabsService->cleanupOldAudioFiles($hours);
        
        $this->info('Audio cleanup completed successfully!');
        
        return Command::SUCCESS;
    }
}
