<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Force HTTPS when in production or when the request is already secure
        // This ensures all URLs generated by Laravel use HTTPS, resolving Mixed Content errors
        // when the application is behind a reverse proxy (e.g., Traefik)
        // Skip forcing HTTPS for localhost development
        if ((config('app.env') === 'production' || request()->secure()) && 
            !str_contains(config('app.url'), 'localhost') && 
            !str_contains(config('app.url'), '127.0.0.1')) {
            URL::forceScheme('https');
        }
    }
}
